# Generated by Django 4.0.2 on 2022-02-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_rename_works_check'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='Work',
        ),
    ]
