# Generated by Django 4.0.2 on 2022-02-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_rename_check_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
