# Generated by Django 4.0.2 on 2022-02-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_work_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='pdf',
            field=models.FileField(blank=True, default='default.png', upload_to='works/media/'),
        ),
    ]
