# Generated by Django 4.0.2 on 2022-02-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_work_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='pdf',
            field=models.FileField(blank=True, default='default.png', upload_to='media/'),
        ),
    ]
