# Generated by Django 4.0.2 on 2022-02-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_alter_work_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='pdf',
            new_name='zip_file',
        ),
    ]
