# Generated by Django 4.0.2 on 2022-02-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_rename_pdf_work_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='zip_file',
        ),
        migrations.AddField(
            model_name='work',
            name='rar_file',
            field=models.FileField(blank=True, default='default.rar', upload_to='media/'),
        ),
    ]
